// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    '[...all]': typeof import('./pages/[...all].vue')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Hi: typeof import('./pages/hi/index.vue')['default']
    Jajal: typeof import('./pages/hi/components/Jajal.vue')['default']
    LinkAv: typeof import('./components/atoms/LinkAv.vue')['default']
    NavbarMv: typeof import('./components/molecules/NavbarMv.vue')['default']
    README: typeof import('./components/README.md')['default']
    SideNavbarMv: typeof import('./components/molecules/SideNavbarMv.vue')['default']
    Undefined: typeof import('./pages/index.vue')['default']
  }
}

export { }
